Ingredient.destroy_all

INGREDIENTS = [
  ['Garlic', 'Produce'],
  ['Lemon', 'Produce'],
  ['Lime', 'Produce'],
  ['Apple', 'Produce'],
  ['Butternut Squash', 'Produce'],
  ['Spinach', 'Produce'],
  ['Romaine Lettuce', 'Produce'],
  ['Rutabaga', 'Produce'],
  ['Carrots', 'Produce'],
  ['Cilantro', 'Produce'],
  ['Raspberries', 'Produce'],
  ['Blueberries', 'Produce'],
  ['Blackberries', 'Produce'],
  ['Parsley, fresh', 'Produce'],
  ['Basil, fresh', 'Produce'],
  ['Mint, fresh', 'Produce'],
  ['Tomatoes', 'Produce'],
  ['Potatoes', 'Produce'],
  ['Sweet Potatoes', 'Produce'],
  ['Yellow Onion', 'Produce'],
  ['Red Onion', 'Produce'],
  ['Green Onion', 'Produce'],
  ['Bell Pepper', 'Produce'],
  ['Jalapeno', 'Produce'],
]
